name: CI Pipeline

# Se ejecuta en push a main/develop/dev y en todos los PRs
on:
  push:
    branches: [main, develop, dev]
  pull_request:
    branches: [main, develop, dev]

jobs:
  # Job 1: Validar código y pruebas
  test:
    name: Test & Lint
    runs-on: ubuntu-latest

    # Servicio de PostgreSQL para las pruebas
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # 1. Checkout del código
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup de Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      # 3. Instalar dependencias
      - name: Install dependencies
        run: npm ci

      # 4. Linter (ESLint)
      - name: Run ESLint
        run: npm run lint

      # 5. Formateo (Prettier check)
      - name: Check code formatting
        run: npx prettier --check "src/**/*.ts" "test/**/*.ts"

      # 6. Build del proyecto
      - name: Build project
        run: npm run build

      # 7. Ejecutar pruebas unitarias con coverage
      # Jest automáticamente valida los umbrales configurados en jest.config.js
      - name: Run tests with coverage
        run: npm run test:cov
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_db
          JWT_SECRET: test-jwt-secret-key-for-ci
